AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    twitterPollerRetweeter
    Sample SAM Template for twitterPollerRetweeter
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 30


Resources:

    TwitterPollerFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: hello_world/build/
            Handler: twitterRetweet.lambda_handler
            Runtime: python3.6
            AutoPublishAlias: live
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    TweetSearchString: 'AWS Lambda'
            Policies:
                - CloudWatchPutMetricPolicy: {}
            Tracing: Active
            Events:
                TwitterPollerEvent:
                    Type: Schedule
                    Properties:
                        Schedule: rate(5 minutes)

Outputs:
    TwitterPollerFunction:
      Description: "TwitterPoller Lambda Function ARN"
      Value: !GetAtt TwitterPollerFunction.Arn

    TwitterPollerFunctionIamRole:
      Description: "Implicit IAM Role created for TwitterPoller function"
      Value: !GetAtt TwitterPollerFunctionRole.Arn
